name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Process uaib placeholders
        run: node build.js
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  # Lighthouse audit job
  lighthouse:
    runs-on: ubuntu-latest
    needs: deploy
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Wait for deployment
        run: sleep 60
      
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.12.x
      
      - name: Create results directory
        run: mkdir -p results/lighthouse
      
      - name: Run Lighthouse CI
        # Continue even if Lighthouse assertions fail to ensure results are uploaded for AI analysis
        run: |
          echo "Running Lighthouse CI..."
          lhci autorun || echo "Lighthouse assertions failed, but continuing to upload results for AI analysis"
        continue-on-error: true
      
      - name: Check if results were generated
        run: |
          if [ -d "results/lighthouse" ] && [ "$(ls -A results/lighthouse)" ]; then
            echo "Lighthouse results found:"
            ls -la results/lighthouse/
          else
            echo "No Lighthouse results found"
          fi
      
      - name: Upload Lighthouse results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-results
          path: results/lighthouse/
          retention-days: 30
          if-no-files-found: warn
      
      - name: Commit Lighthouse results
        if: always()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add results/lighthouse/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add Lighthouse audit results [skip ci]"
            git push
          fi

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4